=== DragonKnightOfBreeze/BBCode/src/main/resources/schemas/schema.dtd
<!ELEMENT schema (description|url|tags)*>
<!ELEMENT description (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT tags (tag)*>
<!ELEMENT tag (description|attributes|attribute)*>
<!ATTLIST tag
    childNames CDATA #IMPLIED
    inline CDATA #IMPLIED
    name CDATA #REQUIRED
    parentNames CDATA #IMPLIED
    textType CDATA #IMPLIED>
<!ELEMENT attributes (attribute)*>
<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute
    name CDATA #IMPLIED
    optional CDATA #IMPLIED
    swap CDATA #IMPLIED
    type CDATA #REQUIRED>

=== DragonKnightOfBreeze/BBCode/src/main/resources/schemas/standard.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schema SYSTEM "schema.dtd">
<schema>
  <description>Standard BBCode language schema.</description>
  <url>https://www.bbcode.org/reference.php</url>
  <tags>
    <tag name="h1">
      <description>Heading 1</description>
    </tag>
    <tag name="h2">
      <description>Heading 2</description>
    </tag>
    <tag name="h3">
      <description>Heading 3</description>
    </tag>
    <tag name="h4">
      <description>Heading 4</description>
    </tag>
    <tag name="h5">
      <description>Heading 5</description>
    </tag>
    <tag name="h6">
      <description>Heading 6</description>
    </tag>
    <tag name="line" inline="true">
      <description>Horizontal line</description>
    </tag>
    <tag name="b">
      <description>Makes {text} bold</description>
    </tag>
    <tag name="i">
      <description>Makes {text} italic</description>
    </tag>
    <tag name="u">
      <description>Underlines {text}</description>
    </tag>
    <tag name="s">
      <description>Create a strikethrough on {text}</description>
    </tag>
    <tag name="style">
      <attributes>
        <attribute name="size" type="numberPx" optional="true"/>
        <attribute name="color" type="color" optional="true"/>
      </attributes>
    </tag>
    <tag name="size">
      <attribute type="number"/>
      <description>Changes the font-size of {text}</description>
    </tag>
    <tag name="color">
      <attribute type="color"/>
      <description>Changes the color of {text}</description>
    </tag>
    <tag name="center">
      <description>Centers {text} on screen</description>
    </tag>
    <tag name="left">
      <description>Left aligns {text} on screen</description>
    </tag>
    <tag name="right">
      <description>Right aligns {text} on screen</description>
    </tag>
    <tag name="quote">
      <attribute type="string" optional="true"/>
      <description>Creates a quotation box containing {text}</description>
    </tag>
    <tag name="spoiler">
      <attribute type="string" optional="true"/>
      <description>
        Creates a spoiler section (a box) that is by default collapsed until you click a button or the box itself
        to expand it to show the {text}
      </description>
    </tag>
    <tag name="url">
      <attribute type="url" optional="true" swap="true"/>
      <description>Makes a link to {url}</description>
    </tag>
    <tag name="img" textType="url">
      <attribute type="size" optional="true"/>
      <attributes>
        <attribute name="width" type="number"/>
        <attribute name="height" type="number"/>
        <attribute name="title" type="string" optional="true"/>
        <attribute name="alt" type="string" optional="true"/>
      </attributes>
      <description>Shows the image indicated by {url}</description>
    </tag>
    <tag name="ul" childNames="li,*">
      <description>Displays an unordered list of {items}</description>
    </tag>
    <tag name="ol" childNames="li,*">
      <description>Displays an ordered list of {items}</description>
    </tag>
    <tag name="list" childNames="li,*">
      <description>Displays an ordered list of {items}</description>
    </tag>
    <tag name="li" parentNames="ul,ol,list">
      <description>Specifies an {item} within a list</description>
    </tag>
    <tag name="*" parentNames="ul,ol,list" inline="true">
      <description>Specifies an {item} within a list (Shorthand)</description>
    </tag>
    <tag name="code">
      <attribute type="language" optional="true"/>
      <description>Meant for rendering code snippets</description>
    </tag>
    <tag name="pre">
      <description>Renders the {text} while maintaining all white spacing</description>
    </tag>
    <tag name="table" childNames="tr">
      <description>Show a table with {rows} in it</description>
    </tag>
    <tag name="tr" parentNames="table" childNames="th,td">
      <description>Renders a table row containing {cells}</description>
    </tag>
    <tag name="th" parentNames="tr">
      <description>Shows {content} in a table (heading) cell</description>
    </tag>
    <tag name="td" parentNames="tr">
      <description>Shows {content} in a table (heading) cell</description>
    </tag>
    <tag name="youtube" textType="youtubeId">
      <description>Shows the YouTube video indicated by {id}</description>
    </tag>
  </tags>
</schema>
